### PR TITLE
automatic planet sprite creation

### PR DESCRIPTION
**Pull request by YPetremann**
It foreach on every existing planet to create the corresponding sprite, it also manage multiple layers if available (not really tested multiple layers but mapping are 1:1).

### CODE REVIEW

**Comment by PlexPt** [comment]
you need do it in data-final-fix

**Comment by PlexPt** [comment]
icon_size should not be hard code

**Comment by Nauviax** [comment]
I believe the only difference this version has over the current (updated) branch is now just the planet.starmap_icons / layers support right? Do you know of any mods that make use of this so I can test it? The current implementation seems to work fine without making use of it.

**Comment by Nauviax** [comment]
Closing this request due to inactivity, and I believe the functionality has basically been added already.

**Pull request closed without merging**
